#!/usr/bin/env python3
"""Собирает src/cg_httpdl_blob.z из src/httpdl_blob.h.

src/httpdl_blob.h — это C++-массив `static const uint8_t kHttpdlBlob[]`,
который codegen_httpdl.cpp:118 кладёт в .text через `for (b : kHttpdlBlob)
emit8(b)`. В .z нет способа описать бинарный массив иначе, чем строковым
литералом, поэтому байты выкладываются кусками по CHUNK байт: каждый кусок —
одна строка-аргумент `cgHttpDlPutChunk("...", n)`.

Ограничения, которые диктует selfhost-лексер (selfhost/lexer.z):

  * поддерживаются только `\\n \\t \\r \\\\ \\" \\0` — поэтому перевод
    строки и возврат каретки ОБЯЗАТЕЛЬНО экранируются: литерал не должен
    содержать сырых 0x0A/0x0D, иначе одна инструкция растянется на много
    строк и zffi_preprocessIncludes увидит внутри литерала строки,
    похожие на директивы;
  * `"` и `\\` экранируются, иначе литерал оборвётся;
  * прочие байты (в том числе 0x00..0x1F и 0x80..0xFF) кладутся сырыми —
    лексер принимает их внутри литерала как есть. Файл пишется в бинарном
    режиме (latin-1), чтобы байты >= 0x80 не размножились в UTF-8.

Сам файл — зеркало tools/gen_httpdl_blob.sh: правится только генератором.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HDR = os.path.join(ROOT, "src", "httpdl_blob.h")
OUT = os.path.join(ROOT, "src", "cg_httpdl_blob.z")

CHUNK = 65536

ESCAPES = {
    0x00: b"\\0",
    0x09: b"\\t",
    0x0A: b"\\n",
    0x0D: b"\\r",
    0x22: b'\\"',
    0x5C: b"\\\\",
}


def escape(data: bytes) -> bytes:
    out = bytearray()
    for b in data:
        esc = ESCAPES.get(b)
        out += esc if esc is not None else bytes((b,))
    return bytes(out)


def parse_header(path: str):
    text = open(path, encoding="utf-8", errors="strict").read()
    m = re.search(r"^#define\s+HTTPDL_BLOB_ENTRY\s+(0x[0-9A-Fa-f]+)", text, re.M)
    if not m:
        raise SystemExit("gen_httpdl_blob_z: HTTPDL_BLOB_ENTRY не найден в %s" % path)
    entry = int(m.group(1), 16)
    m = re.search(r"static const uint8_t kHttpdlBlob\[\] = \{", text)
    if not m:
        raise SystemExit("gen_httpdl_blob_z: kHttpdlBlob[] не найден в %s" % path)
    end = text.index("};", m.end())
    body = text[m.end():end]
    data = bytes(int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]{2})", body))
    return entry, data


HEADER = """\
# Auto-generated by tools/gen_httpdl_blob_z.py from src/httpdl_blob.h - DO NOT EDIT.
#
# Байты freestanding HTTP/HTTPS download-движка (без libc): в .text их кладёт
# cgEmitHttpDlBlob() ровно так, как codegen_httpdl.cpp:116..122 кладёт
# kHttpdlBlob[] — сначала NOP-выравнивание на 16, потом сами байты, потом
# labelPositions[httpDlEntryLabel] = blobStart + HTTPDL_BLOB_ENTRY.
#
# Каждый cgHttpDlPutChunk — один кусок CHUNK байт; длина передаётся явно,
# потому что в середине blob'а встречаются NUL'ы и strLen() на таком
# литерале остановился бы на первом из них. В сам файл заложено и то, что
# лексер умеет только \\n \\t \\r \\\\ \\" \\0 — сырых переводов строки внутри
# литерала нет, поэтому он укладывается в одну строку исходника.

# codegen.h:744..745 — члены Codegen (cgHttpDlUsed живёт в cg_emit.z рядом с
# cgTlsUsed/cgJsUsed). Сбрасывает их cgFreshState().
var cgHttpDlBlobEmitted: int = 0
var cgHttpDlEntryLabel: int = -1

const CG_HTTPDL_BLOB_ENTRY: int = 0x%X

# один кусок blob'а в .text (C++: for (uint8_t b : kHttpdlBlob) emit8(b))
func cgHttpDlPutChunk(s: int, n: int)
    cgCodeAppend(s, n)
end

func cgHttpDlEmitBlobBytes()
"""


EPILOGUE = """
# codegen_httpdl.cpp:108..123 — append the blob to .text and bind the label
# the `call rel32` sites in tryHttpDlCall jump through. Runs after function
# codegen but before fixupSectionRVAs/resolveJmpFixups (codegen.cpp:8723).
func cgEmitHttpDlBlob()
    if cgHttpDlBlobEmitted != 0
        return
    end
    cgHttpDlBlobEmitted = 1
    if cgHttpDlEntryLabel < 0
        cgHttpDlEntryLabel = newLabel()
    end

    # The embedded TLS core uses 16-byte-aligned SIMD constant loads
    # (movdqa from .text). Align the section so those offsets stay valid
    # regardless of where the blob lands in the final image.
    while cgCodeLen % 16 != 0
        emit8(0x90)
    end
    var blobStart: int = cgCodeLen
    cgHttpDlEmitBlobBytes()
    if cgHttpDlEntryLabel >= 0 && cgHttpDlEntryLabel < 8192
        cgLabelPos[cgHttpDlEntryLabel] = blobStart + CG_HTTPDL_BLOB_ENTRY
    end
end
"""


def main() -> int:
    if not os.path.exists(HDR):
        raise SystemExit("gen_httpdl_blob_z: нет %s" % HDR)
    entry, data = parse_header(HDR)
    if not data:
        raise SystemExit("gen_httpdl_blob_z: пустой kHttpdlBlob[]")

    out = bytearray((HEADER % entry).encode("utf-8"))
    total = len(data)
    off = 0
    while off < total:
        n = min(CHUNK, total - off)
        chunk = data[off:off + n]
        out += b'    cgHttpDlPutChunk("' + escape(chunk) + b'", %d)\n' % n
        off += n
    out += b"end\n"
    out += EPILOGUE.encode("utf-8")

    with open(OUT, "wb") as f:
        f.write(out)
    sys.stdout.write(
        "gen_httpdl_blob_z: %s (%d байт, %d кусков, entry=0x%X)\n"
        % (os.path.relpath(OUT, ROOT), total, (total + CHUNK - 1) // CHUNK, entry)
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
