#!/usr/bin/env python3
"""Собирает src/cg_js_blob.z из src/js_blob.h.

src/js_blob.h — это C++-массив `static const uint8_t kJsBlob[]`
(189816 байт freestanding JS-движка из tools/jsrt.c + tools/js_host_linux.c),
который codegen_js.cpp:183..227 кладёт в .text:

  * выравнивание базы блоба на 16 **нулями** (`while (blobStart % 16)
    emit8(0)` — не NOP: движок компилировался под 16-байтную базу, но
    aligned SSE тут не грузит константы из .text, а 0x90 в этом месте
    изменил бы смещения, на которые опирается bss-pad);
  * сами байты kJsBlob;
  * zero-fill .bss блоба: `code.resize(code.size() + (kJs__bss_end -
    kJsBlobSize), 0)` — это 17633128 нулей (statics + 4 MiB arena),
    живущих в нашем RWX .text;
  * `labelPositions[jsEntryLabel] = blobStart + kJsJsrt_entry`;
  * для Linux: `labelPositions[jsHostStubLabel[slot]] = blobStart + sym`
    для каждой строки kJsHostLinux (реализация host-колбэка уже лежит
    внутри блоба — tools/js_host_linux.c), затем `emitLabel(jsHostFlagLabel);
    emit8(0)` — байт-флаг «таблица уже установлена».

В .z нет способа описать бинарный массив иначе, чем строковым литералом,
поэтому байты выкладываются кусками по CHUNK байт: каждый кусок — одна
строка-аргумент `cgJsPutChunk("...", n)`.

Ограничения selfhost-лексера (selfhost/lexer.z) — те же, что у
tools/gen_tls_blob_z.py: внутри литерала только \\n \\t \\r \\\\ \\" \\0,
сырых 0x0A/0x0D быть не должно, прочие байты кладутся сырыми. Файл
пишется в бинарном режиме.

Сам файл — зеркало tools/gen_tls_blob_z.py: правится только генератором.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HDR = os.path.join(ROOT, "src", "js_blob.h")
OUT = os.path.join(ROOT, "src", "cg_js_blob.z")

CHUNK = 8192

ESCAPES = {
    0x00: b"\\0",
    0x09: b"\\t",
    0x0A: b"\\n",
    0x0D: b"\\r",
    0x22: b'\\"',
    0x5C: b"\\\\",
}

# codegen_js.cpp:85..100 — kJsHostLinux: слот g_host_fn[] -> смещение
# реализации внутри блоба. Ровно эти 14 строк есть в C++ таблице.
HOST_SYMS = [
    ("FS_READ", 0, "kJsJs_host_fs_read"),
    ("FS_WRITE", 1, "kJsJs_host_fs_write"),
    ("FS_EXISTS", 2, "kJsJs_host_fs_exists"),
    ("GET_CWD", 3, "kJsJs_host_get_cwd"),
    ("PRINT", 12, "kJsJs_host_print"),
    ("EXEC", 13, "kJsJs_host_exec"),
    ("FS_MKDIR", 14, "kJsJs_host_fs_mkdir"),
    ("FS_READDIR", 15, "kJsJs_host_fs_readdir"),
    ("FS_UNLINK", 16, "kJsJs_host_fs_unlink"),
    ("SLEEP", 17, "kJsJs_host_sleep"),
    ("FS_STAT", 18, "kJsJs_host_fs_stat"),
    ("ENV", 20, "kJsJs_host_env"),
    ("ARGS", 21, "kJsJs_host_args"),
    ("UNAME", 22, "kJsJs_host_uname"),
]


def escape(data: bytes) -> bytes:
    out = bytearray()
    for b in data:
        esc = ESCAPES.get(b)
        out += esc if esc is not None else bytes((b,))
    return bytes(out)


def parse_header(path: str):
    text = open(path, encoding="utf-8").read()

    def u32(name):
        m = re.search(r"static constexpr uint32_t %s = (0x[0-9A-Fa-f]+);" % name, text)
        if not m:
            raise SystemExit("gen_js_blob_z: %s не найден в %s" % (name, path))
        return int(m.group(1), 16)

    entry = u32("kJsJsrt_entry")
    bss_end = u32("kJs__bss_end")

    m = re.search(r"static constexpr uint32_t kJsBlobSize = (\d+);", text)
    if not m:
        raise SystemExit("gen_js_blob_z: kJsBlobSize не найден")
    size = int(m.group(1))

    m = re.search(r"static const uint8_t kJsBlob\[\] = \{", text)
    if not m:
        raise SystemExit("gen_js_blob_z: kJsBlob[] не найден в %s" % path)
    end = text.index("};", m.end())
    body = text[m.end():end]
    data = bytes(int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]{2})", body))
    if len(data) != size:
        raise SystemExit(
            "gen_js_blob_z: разобрано %d байт, kJsBlobSize = %d" % (len(data), size)
        )

    syms = []
    for name, slot, cname in HOST_SYMS:
        syms.append((name, slot, u32(cname)))
    return entry, bss_end, size, data, syms


HEADER = """\
# Auto-generated by tools/gen_js_blob_z.py from src/js_blob.h - DO NOT EDIT.
#
# Байты freestanding JS-движка (tools/jsrt.c + tools/js_host_linux.c):
# в .text их кладёт cgEmitJsBlob() ровно так, как codegen_js.cpp:183..227
# кладёт kJsBlob[] — сначала НУЛЕВОЕ выравнивание базы на 16, потом сами
# байты, потом zero-fill .bss блоба (statics + 4 MiB arena, суммарно
# %d байт), потом
# labelPositions[jsEntryLabel] = blobStart + kJsJsrt_entry.
#
# .text для js-приложений делается записываемым (p_flags уже считает
# cgJsUsed в cg_elf.z); флаг «host-таблица установлена» живёт байтом
# сразу за блобом, в этом же RWX .text.
#
# Каждый cgJsPutChunk — один кусок CHUNK байт; длина передаётся явно,
# потому что в середине blob'а встречаются NUL'ы и strLen() на таком
# литерале остановился бы на первом из них. Лексер умеет только
# \\n \\t \\r \\\\ \\" \\0 — сырых переводов строки внутри литерала нет,
# поэтому он укладывается в одну строку исходника.
#
# codegen.h — члены Codegen jsBlobEmitted/jsEntryLabel/jsHostFlagLabel
# (рядом с cgJsUsed в cg_emit.z / здесь). Сбрасывает их cgFreshState().
var cgJsBlobEmitted: int = 0
var cgJsEntryLabel: int = -1
var cgJsHostFlagLabel: int = -1
var cgJsHostStubLabel: [24]int

const CG_JS_BLOB_ENTRY: int = 0x%X
const CG_JS_BSS_END: int = 0x%X
const CG_JS_BLOB_SIZE: int = %d
const CG_JS_BSS_PAD: int = %d

# один кусок blob'а в .text (C++: for (uint8_t b : kJsBlob) emit8(b))
func cgJsPutChunk(s: int, n: int)
    cgCodeAppend(s, n)
end

func cgJsEmitBlobBytes()
"""


EPILOGUE = """
# codegen_js.cpp:85..100 — kJsHostLinux: слот g_host_fn[] -> смещение
# реализации внутри блоба. В C++ это массив пар, здесь — та же таблица
# в виде функции (в .z нет структур/параллельных инициализированных
# массивов). 0 означает «слот не установлен на Linux» (net/tls — они в
# kJsHostLinux отсутствуют, движок деградирует мягко).
func cgJsHostSym(slot: int) -> int
"""

HOST_EPILOGUE = """
    return 0
end

# codegen_js.cpp:85..100 — порядок строк kJsHostLinux: cgTryJsCall веткой
# linuxHosts идёт по этому массиву и для каждой строки делает installHost(h.slot).
# i = индекс строки (0..13), -1 = конец таблицы.
func cgJsHostSlotAt(i: int) -> int
"""

SLOT_AFTER = """
    return -1
end

# codegen_js.cpp:201 — code.resize(code.size() + pad, 0): .bss блоба
# (statics + 4 MiB arena) обнуляется прямо в нашем RWX .text. 17.6 МБ
# нулей, поэтому не по одному emit8, а одним cgEnsure + poke8.
func cgJsEmitZeroes(n: int)
    if n <= 0
        return
    end
    cgEnsure(n)
    if cgCodeLen + n > cgCodeCap
        return
    end
    var i: int = 0
    while i < n
        poke8(cgCode + cgCodeLen + i, 0)
        i = i + 1
    end
    cgCodeLen = cgCodeLen + n
end

# codegen_js.cpp:183..227 — append the blob to .text and bind the labels
# the `call rel32` sites in cgTryJsCall jump through. Runs after function
# codegen but before fixupSectionRVAs/resolveJmpFixups (codegen.cpp:8727).
# Вызывается при jsUsed && !libOutput.
func cgEmitJsBlob()
    if cgJsBlobEmitted != 0
        return
    end
    cgJsBlobEmitted = 1
    if cgJsEntryLabel < 0
        cgJsEntryLabel = newLabel()
    end

    # C++: while (blobStart % 16) emit8(0); — НУЛИ, не NOP: так же, как
    # в C++, и это третий образец подряд со своим выравниванием
    # (disasm — нули, httpdl/tls — NOP, js — нули).
    while cgCodeLen % 16 != 0
        emit8(0)
    end
    var blobStart: int = cgCodeLen
    cgJsEmitBlobBytes()

    # C++: code.resize(code.size() + (kJs__bss_end - kJsBlobSize), 0)
    if CG_JS_BSS_END > CG_JS_BLOB_SIZE
        cgJsEmitZeroes(CG_JS_BSS_END - CG_JS_BLOB_SIZE)
    end

    if cgJsEntryLabel >= 0 && cgJsEntryLabel < 8192
        cgLabelPos[cgJsEntryLabel] = blobStart + CG_JS_BLOB_ENTRY
    end

    # Linux (codegen_js.cpp:210..222): каждый установленный слот указывает
    # прямо на реализацию внутри блоба, и после таблицы пишется байт-флаг
    # «уже установлено» (его же читает хвост prologue-а первого js_eval).
    if cgJsHostFlagLabel >= 0
        var slot: int = 0
        while slot < 24
            var sym: int = cgJsHostSym(slot)
            if sym != 0
                if cgJsHostStubLabel[slot] >= 0 && cgJsHostStubLabel[slot] < 8192
                    cgLabelPos[cgJsHostStubLabel[slot]] = blobStart + sym
                end
            end
            slot = slot + 1
        end
        emitLabel(cgJsHostFlagLabel)
        emit8(0)
    end
end
"""


def main() -> int:
    if not os.path.exists(HDR):
        raise SystemExit("gen_js_blob_z: нет %s" % HDR)
    entry, bss_end, size, data, syms = parse_header(HDR)
    if not data:
        raise SystemExit("gen_js_blob_z: пустой kJsBlob[]")

    pad = bss_end - size
    if pad < 0:
        raise SystemExit("gen_js_blob_z: kJs__bss_end < kJsBlobSize")

    out = bytearray((HEADER % (pad, entry, bss_end, size, pad)).encode("utf-8"))
    total = len(data)
    off = 0
    while off < total:
        n = min(CHUNK, total - off)
        chunk = data[off:off + n]
        out += b'    cgJsPutChunk("' + escape(chunk) + b'", %d)\n' % n
        off += n
    out += b"end\n"

    out += EPILOGUE.encode("utf-8")
    for name, slot, sym in syms:
        out += (
            "    if slot == %d\n"
            "        return 0x%X  # %s (kJsJs_host_%s)\n"
            "    end\n" % (slot, sym, name, name.lower())
        ).encode("utf-8")
    out += HOST_EPILOGUE.encode("utf-8")
    for idx, (_name, slot, _sym) in enumerate(syms):
        out += (
            "    if i == %d\n"
            "        return %d\n"
            "    end\n" % (idx, slot)
        ).encode("utf-8")
    out += SLOT_AFTER.encode("utf-8")

    with open(OUT, "wb") as f:
        f.write(out)
    sys.stdout.write(
        "gen_js_blob_z: %s (%d байт, %d кусков, entry=0x%X, bss_end=0x%X, pad=%d)\n"
        % (os.path.relpath(OUT, ROOT), total, (total + CHUNK - 1) // CHUNK,
           entry, bss_end, pad)
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
