#!/usr/bin/env python3
"""Собирает src/cg_disasm_blob.z из src/disasm_blob.h.

src/disasm_blob.h — это C++-массив `static const uint8_t kDsBlob[]`,
который codegen_disasm.cpp:115 кладёт в .text через `for (b : kDsBlob)
emit8(b)`, а :117..119 резолвит `labelPositions[disasmEntryLabel] =
blobStart + kDsBlobEntry`. В .z нет способа описать бинарный массив иначе,
чем строковым литералом, поэтому байты выкладываются кусками по CHUNK
байт: каждый кусок — одна строка-аргумент `cgDisasmPutChunk("...", n)`.

Ограничения, которые диктует selfhost-лексер (selfhost/lexer.z):

  * поддерживаются только `\\n \\t \\r \\\\ \\" \\0` — поэтому перевод
    строки и возврат каретки ОБЯЗАТЕЛЬНО экранируются: литерал не должен
    содержать сырых 0x0A/0x0D, иначе одна инструкция растянется на много
    строк и zffi_preprocessIncludes увидит внутри литерала строки,
    похожие на директивы;
  * `"` и `\\` экранируются, иначе литерал оборвётся;
  * прочие байты (в том числе 0x00..0x1F и 0x80..0xFF) кладутся сырыми —
    лексер принимает их внутри литерала как есть. Файл пишется в бинарном
    режиме, поэтому байты >= 0x80 не размножатся в UTF-8 (как в
    src/cg_httpdl_blob.z и в литерале cgSoundLutAppend).

Сам файл — зеркало tools/gen_httpdl_blob_z.py: правится только генератором.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HDR = os.path.join(ROOT, "src", "disasm_blob.h")
OUT = os.path.join(ROOT, "src", "cg_disasm_blob.z")

CHUNK = 8192

ESCAPES = {
    0x00: b"\\0",
    0x09: b"\\t",
    0x0A: b"\\n",
    0x0D: b"\\r",
    0x22: b'\\"',
    0x5C: b"\\\\",
}


def escape(data: bytes) -> bytes:
    out = bytearray()
    for b in data:
        esc = ESCAPES.get(b)
        out += esc if esc is not None else bytes((b,))
    return bytes(out)


def parse_header(path: str):
    text = open(path, encoding="utf-8").read()
    m = re.search(r"static constexpr uint32_t kDsBlobEntry = (kDs\w+);", text)
    if not m:
        raise SystemExit("gen_disasm_blob_z: kDsBlobEntry не найден в %s" % path)
    sym = m.group(1)
    m = re.search(r"static constexpr uint32_t %s = (0x[0-9A-Fa-f]+);" % sym, text)
    if not m:
        raise SystemExit("gen_disasm_blob_z: значение %s не найдено" % sym)
    entry = int(m.group(1), 16)
    m = re.search(r"static const uint8_t kDsBlob\[\] = \{", text)
    if not m:
        raise SystemExit("gen_disasm_blob_z: kDsBlob[] не найден в %s" % path)
    end = text.index("};", m.end())
    body = text[m.end():end]
    data = bytes(int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]{2})", body))
    m = re.search(r"static constexpr uint32_t kDsBlobSize = (\d+);", text)
    if not m:
        raise SystemExit("gen_disasm_blob_z: kDsBlobSize не найден")
    size = int(m.group(1))
    if len(data) != size:
        raise SystemExit(
            "gen_disasm_blob_z: разобрано %d байт, kDsBlobSize = %d" % (len(data), size)
        )
    return entry, data


HEADER = """\
# Auto-generated by tools/gen_disasm_blob_z.py from src/disasm_blob.h - DO NOT EDIT.
#
# Байты freestanding x86-64 дизассемблера (Intel + AT&T, без libc): в .text
# их кладёт cgEmitDisasmBlob() ровно так, как codegen_disasm.cpp:108..120
# кладёт kDsBlob[] — сначала NOP-выравнивание на 16, потом сами байты, потом
# labelPositions[disasmEntryLabel] = blobStart + kDsBlobEntry.
#
# Внутри blob'а живут и два mode-глобала (g_intel/g_addrPfx), поэтому .text
# обязан быть RWX — p_flags уже считает cgDisasmUsed (cg_elf.z).
#
# Каждый cgDisasmPutChunk — один кусок CHUNK байт; длина передаётся явно,
# потому что в середине blob'а встречаются NUL'ы и strLen() на таком
# литерале остановился бы на первом из них. Лексер умеет только
# \\n \\t \\r \\\\ \\" \\0 — сырых переводов строки внутри литерала нет,
# поэтому он укладывается в одну строку исходника.

# codegen.h:803..805 — члены Codegen (cgDisasmUsed живёт в cg_emit.z).
# Сбрасывает их cgFreshState().
var cgDisasmBlobEmitted: int = 0
var cgDisasmEntryLabel: int = -1

const CG_DISASM_BLOB_ENTRY: int = 0x%X

# один кусок blob'а в .text (C++: for (uint8_t b : kDsBlob) emit8(b))
func cgDisasmPutChunk(s: int, n: int)
    cgCodeAppend(s, n)
end

func cgDisasmEmitBlobBytes()
"""


EPILOGUE = """
# codegen_disasm.cpp:108..120 — append the blob to .text and bind the label
# the `call rel32` sites in cgTryDisasmCall jump through. Runs after function
# codegen but before fixupSectionRVAs/resolveJmpFixups (codegen.cpp:8736).
func cgEmitDisasmBlob()
    if cgDisasmBlobEmitted != 0
        return
    end
    cgDisasmBlobEmitted = 1
    if cgDisasmEntryLabel < 0
        cgDisasmEntryLabel = newLabel()
    end

    # C++: while (blobStart % 16 != 0) { emit8(0); ... } — НУЛЕВОЙ padding,
    # не NOP: байты выравнивания в .text должны совпадать с эталоном байт-в-байт.
    while cgCodeLen % 16 != 0
        emit8(0)
    end
    var blobStart: int = cgCodeLen
    cgDisasmEmitBlobBytes()
    if cgDisasmEntryLabel >= 0 && cgDisasmEntryLabel < 8192
        cgLabelPos[cgDisasmEntryLabel] = blobStart + CG_DISASM_BLOB_ENTRY
    end
end
"""


def main() -> int:
    if not os.path.exists(HDR):
        raise SystemExit("gen_disasm_blob_z: нет %s" % HDR)
    entry, data = parse_header(HDR)
    if not data:
        raise SystemExit("gen_disasm_blob_z: пустой kDsBlob[]")

    out = bytearray((HEADER % entry).encode("utf-8"))
    total = len(data)
    off = 0
    while off < total:
        n = min(CHUNK, total - off)
        chunk = data[off:off + n]
        out += b'    cgDisasmPutChunk("' + escape(chunk) + b'", %d)\n' % n
        off += n
    out += b"end\n"
    out += EPILOGUE.encode("utf-8")

    with open(OUT, "wb") as f:
        f.write(out)
    sys.stdout.write(
        "gen_disasm_blob_z: %s (%d байт, %d кусков, entry=0x%X)\n"
        % (os.path.relpath(OUT, ROOT), total, (total + CHUNK - 1) // CHUNK, entry)
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
