#!/usr/bin/env python3
"""Собирает src/cg_tls_blob.z из src/tls_blob.h.

src/tls_blob.h — это C++-массив `static const uint8_t kTlsBlob[]`,
который codegen_tls.cpp:109 кладёт в .text через `for (b : kTlsBlob)
emit8(b)`, а :115..117 резолвит `labelPositions[tlsEntryLabel] =
blobStart + kTlstlsrt_entry`. В .z нет способа описать бинарный массив
иначе, чем строковым литералом, поэтому байты выкладываются кусками по
CHUNK байт: каждый кусок — одна строка-аргумент `cgTlsPutChunk("...", n)`.

Ограничения, которые диктует selfhost-лексер (selfhost/lexer.z):

  * поддерживаются только `\\n \\t \\r \\\\ \\" \\0` — поэтому перевод
    строки и возврат каретки ОБЯЗАТЕЛЬНО экранируются: литерал не должен
    содержать сырых 0x0A/0x0D, иначе одна инструкция растянется на много
    строк и zffi_preprocessIncludes увидит внутри литерала строки,
    похожие на директивы;
  * `"` и `\\` экранируются, иначе литерал оборвётся;
  * прочие байты (в том числе 0x00..0x1F и 0x80..0xFF) кладутся сырыми —
    лексер принимает их внутри литерала как есть. Файл пишется в бинарном
    режиме, поэтому байты >= 0x80 не размножатся в UTF-8 (как в
    src/cg_httpdl_blob.z и в литерале cgSoundLutAppend).

Сам файл — зеркало tools/gen_disasm_blob_z.py: правится только генератором.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HDR = os.path.join(ROOT, "src", "tls_blob.h")
OUT = os.path.join(ROOT, "src", "cg_tls_blob.z")

CHUNK = 8192

ESCAPES = {
    0x00: b"\\0",
    0x09: b"\\t",
    0x0A: b"\\n",
    0x0D: b"\\r",
    0x22: b'\\"',
    0x5C: b"\\\\",
}


def escape(data: bytes) -> bytes:
    out = bytearray()
    for b in data:
        esc = ESCAPES.get(b)
        out += esc if esc is not None else bytes((b,))
    return bytes(out)


def parse_header(path: str):
    text = open(path, encoding="utf-8").read()
    m = re.search(r"static constexpr uint32_t kTlstlsrt_entry = (0x[0-9A-Fa-f]+);", text)
    if not m:
        raise SystemExit("gen_tls_blob_z: kTlstlsrt_entry не найден в %s" % path)
    entry = int(m.group(1), 16)
    m = re.search(r"static const uint8_t kTlsBlob\[\] = \{", text)
    if not m:
        raise SystemExit("gen_tls_blob_z: kTlsBlob[] не найден в %s" % path)
    end = text.index("};", m.end())
    body = text[m.end():end]
    data = bytes(int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]{2})", body))
    m = re.search(r"static constexpr uint32_t kTlsBlobSize = (\d+);", text)
    if not m:
        raise SystemExit("gen_tls_blob_z: kTlsBlobSize не найден")
    size = int(m.group(1))
    if len(data) != size:
        raise SystemExit(
            "gen_tls_blob_z: разобрано %d байт, kTlsBlobSize = %d" % (len(data), size)
        )
    return entry, data


HEADER = """\
# Auto-generated by tools/gen_tls_blob_z.py from src/tls_blob.h - DO NOT EDIT.
#
# Байты freestanding TLS 1.2 (ECDHE-RSA-AES128-GCM-SHA256) поверх сырого
# сокета, без libc: в .text их кладёт cgEmitTlsBlob() ровно так, как
# codegen_tls.cpp:99..118 кладёт kTlsBlob[] — сначала NOP-выравнивание
# на 16 (крипто-код грузит SIMD-константы movdqa со смещений внутри
# .text), потом сами байты, потом
# labelPositions[tlsEntryLabel] = blobStart + kTlstlsrt_entry.
#
# .text для tls-приложений делается записываемым (p_flags уже считает
# cgTlsUsed в cg_elf.z) — блоб сам держит io-слоты send/recv/closesocket
# в своей памяти внутри .text.
#
# Каждый cgTlsPutChunk — один кусок CHUNK байт; длина передаётся явно,
# потому что в середине blob'а встречаются NUL'ы и strLen() на таком
# литерале остановился бы на первом из них. Лексер умеет только
# \\n \\t \\r \\\\ \\" \\0 — сырых переводов строки внутри литерала нет,
# поэтому он укладывается в одну строку исходника.

# codegen.h — члены Codegen tlsBlobEmitted/tlsEntryLabel (объявлены рядом
# с cgTlsUsed в cg_emit.z). Сбрасывает их cgFreshState().
var cgTlsBlobEmitted: int = 0
var cgTlsEntryLabel: int = -1

const CG_TLS_BLOB_ENTRY: int = 0x%X

# один кусок blob'а в .text (C++: for (uint8_t b : kTlsBlob) emit8(b))
func cgTlsPutChunk(s: int, n: int)
    cgCodeAppend(s, n)
end

func cgTlsEmitBlobBytes()
"""


EPILOGUE = """
# codegen_tls.cpp:99..118 — append the blob to .text and bind the label
# the `call rel32` sites in cgTryTlsCall/cgEmitTlsIoInit jump through.
# Runs after function codegen but before fixupSectionRVAs/resolveJmpFixups
# (codegen.cpp:8714). Вызывается при (tlsUsed || jsUsed) && !libOutput.
func cgEmitTlsBlob()
    if cgTlsBlobEmitted != 0
        return
    end
    cgTlsBlobEmitted = 1
    if cgTlsEntryLabel < 0
        cgTlsEntryLabel = newLabel()
    end

    # C++: while (code.size() % 16) emit8(0x90); — NOP, не нули: крипто-код
    # blob'а грузит SIMD-константы movdqa со смещений внутри .text, и эти
    # смещения обязаны остаться валидными, куда бы блоб ни сел.
    while cgCodeLen % 16 != 0
        emit8(0x90)
    end
    var blobStart: int = cgCodeLen
    cgTlsEmitBlobBytes()
    if cgTlsEntryLabel >= 0 && cgTlsEntryLabel < 8192
        cgLabelPos[cgTlsEntryLabel] = blobStart + CG_TLS_BLOB_ENTRY
    end
end
"""


def main() -> int:
    if not os.path.exists(HDR):
        raise SystemExit("gen_tls_blob_z: нет %s" % HDR)
    entry, data = parse_header(HDR)
    if not data:
        raise SystemExit("gen_tls_blob_z: пустой kTlsBlob[]")

    out = bytearray((HEADER % entry).encode("utf-8"))
    total = len(data)
    off = 0
    while off < total:
        n = min(CHUNK, total - off)
        chunk = data[off:off + n]
        out += b'    cgTlsPutChunk("' + escape(chunk) + b'", %d)\n' % n
        off += n
    out += b"end\n"
    out += EPILOGUE.encode("utf-8")

    with open(OUT, "wb") as f:
        f.write(out)
    sys.stdout.write(
        "gen_tls_blob_z: %s (%d байт, %d кусков, entry=0x%X)\n"
        % (os.path.relpath(OUT, ROOT), total, (total + CHUNK - 1) // CHUNK, entry)
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
