#!/bin/bash
# Generates src/tls_blob.h from tools/tlsrt.c (freestanding, position-independent
# x86-64 crypto/TLS core). The blob is embedded into every Zenith .exe text
# section and invoked with internal/relative calls (no external fixups, no libc).
#
# ABI notes:
#  - The blob is compiled by the HOST gcc as Linux x86-64 (SysV) code. The
#    Zenith codegen calls blob entry points via `call rel32` after staging
#    arguments into rdi/rsi/rdx/rcx/r8/r9 and results come back in rax.
#  - The blob's own internal calls are SysV; it must NOT call into Windows DLLs
#    with SysV convention. Raw socket I/O goes through two tiny asm stubs in
#    tlsrt.s that translate SysV -> Win64 and jump through function pointers
#    stored in blob .bss (seeded by tlsrt_io_init).
set -euo pipefail

cd "$(dirname "$0")/.."
OUT=src/tls_blob.h
HDR=tools/tlsrt.h
SRC=tools/tlsrt.c
ASM=tools/tlsrt.s
LD=tools/tlsrt.ld

CC=gcc
OBJDIR=/tmp/tlsblob
rm -rf "$OBJDIR"; mkdir -p "$OBJDIR"

$CC -O2 -ffreestanding -fno-stack-protector -fno-ident -fno-asynchronous-unwind-tables \
    -fno-builtin -fpic -fno-common -mno-red-zone -fvisibility=hidden \
    -I"$(dirname $HDR)" -c "$SRC" -o "$OBJDIR/tlsrt.o"
$CC -O2 -ffreestanding -c "$ASM" -o "$OBJDIR/tlsrt_asm.o"

ld -o "$OBJDIR/tlsrt.img" -T "$LD" -e tlsrt_entry \
    "$OBJDIR/tlsrt.o" "$OBJDIR/tlsrt_asm.o"

objcopy -O binary "$OBJDIR/tlsrt.img" "$OBJDIR/tlsrt.bin"

# Extract symbol offsets (VMA addresses, image starts at VMA 0)
python3 - "$OBJDIR/tlsrt.img" "$OBJDIR/tlsrt.bin" "$OUT" <<'PY'
import re, sys
img, binimg, out = sys.argv[1], sys.argv[2], sys.argv[3]
import subprocess
r = subprocess.run(['nm', img], capture_output=True, text=True).stdout
syms = {}
bss_end = 0
for line in r.splitlines():
    p = line.split()
    if len(p) >= 3 and p[1] in 'TtDdBb':
        if p[2] == '__bss_end':
            bss_end = int(p[0], 16)
        # Skip compiler-internal artifacts (clone suffixes like ".constprop.0",
        # ".isra.0") which are not valid C identifier names.
        if '.' in p[2] or p[2].startswith('__'):
            continue
        try: syms[p[2]] = int(p[0], 16)
        except ValueError: pass
data = open(binimg, 'rb').read()
# objcopy -O binary drops the trailing NOBITS .bss (it produces no file bytes for
# it), so the flat image would end right where .bss begins. Every blob global
# (io slots, session pool, cert store) lives in .bss and is written/read through
# RIP-relative addressing (blob offset == VMA), so those writes would land past
# the end of the image -> heap corruption / SEGV when the blob is mmap'd and
# invoked. Pad the image with zeros out to __bss_end so the whole .bss is inside
# the embedded blob (safe, since the PE/ELF linker will place it in a writable
# RWX .text section anyway).
if bss_end > len(data):
    data += b'\x00' * (bss_end - len(data))
# find image sections sizes from objdump -h
r2 = subprocess.run(['objdump', '-h', img], capture_output=True, text=True).stdout
secs = []
for line in r2.splitlines():
    m = re.match(r'\s*\d+\s+([.\w]+)\s+([0-9a-f]+)\s+([0-9a-f]+)', line)
    if m:
        secs.append((m.group(1), int(m.group(2),16), int(m.group(3),16)))
with open(out, 'w') as f:
    f.write('// Auto-generated by tools/gen_tls_blob.sh - DO NOT EDIT\n')
    f.write('// Position-independent freestanding TLS/crypto core (x86-64, SysV-internal).\n')
    f.write('#pragma once\n#include <cstdint>\n\n')
    f.write('// Entry-point offsets into the blob (VMA = blob offset).\n')
    for s, v in sorted(syms.items()):
        f.write('static constexpr uint32_t kTls%s = 0x%x;\n' % (s, v))
    f.write('\n// Exported blob entry points used by codegen_tls.cpp:\n')
    for name, macro in (('tlsrt_entry','TLS_BLOB_ENTRY'),
                        ('tlsrt_send_stub','TLS_BLOB_SEND'),
                        ('tlsrt_recv_stub','TLS_BLOB_RECV'),
                        ('tlsrt_close_stub','TLS_BLOB_CLOSE')):
        v = syms.get(name)
        if v is not None:
            f.write('#define %s 0x%x\n' % (macro, v))
    f.write('\nstatic const uint8_t kTlsBlob[] = {\n')
    # section layout note: .text first, then .rodata/.data/.bss
    # (bss may be zero-only in bin, padded out to __bss_end above).
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        f.write('    ' + ','.join('0x%02x'%b for b in chunk) + ',\n')
    f.write('};\n')
    f.write('static constexpr uint32_t kTlsBlobSize = %d;\n' % len(data))
print('Wrote %s (%d bytes, syms=%d svc=%d, bss_end=0x%x)' % (out, len(data), len(syms), len(secs), bss_end))
PY