#!/bin/bash
# Generates src/js_blob.h from tools/jsrt.c (freestanding, position-independent
# x86-64 JS engine). The blob is embedded into every Zenith .exe text section
# and invoked with internal/relative calls (no external fixups, no libc).
#
# ABI notes:
#  - The blob is compiled by the HOST gcc as Linux x86-64 (SysV) code. The
#    Zenith codegen calls the blob entry via `call rel32` after staging
#    arguments into rdi/rsi/rdx/rcx/r8/r9 and results come back in rax.
#  - The engine uses a 4 MiB arena in .bss (bumped, reset by JS_OP_RESET).
set -euo pipefail

cd "$(dirname "$0")/.."
OUT=src/js_blob.h
SRC=tools/jsrt.c
LD=tools/jsrt.ld

CC=gcc
OBJDIR=/tmp/jsblob
rm -rf "$OBJDIR"; mkdir -p "$OBJDIR"

$CC -O2 -ffreestanding -fno-stack-protector -fno-ident -fno-asynchronous-unwind-tables \
    -fno-builtin -fpic -fno-common -mno-red-zone \
    -Itools -c "$SRC" -o "$OBJDIR/jsrt.o"

ld -o "$OBJDIR/jsrt.img" -T "$LD" -e jsrt_entry "$OBJDIR/jsrt.o"

objcopy -O binary "$OBJDIR/jsrt.img" "$OBJDIR/jsrt.bin"

# Extract symbol offsets (VMA addresses, image starts at VMA 0)
python3 - "$OBJDIR/jsrt.img" "$OBJDIR/jsrt.bin" "$OUT" <<'PY'
import re, sys
img, binimg, out = sys.argv[1], sys.argv[2], sys.argv[3]
import subprocess
r = subprocess.run(['nm', img], capture_output=True, text=True).stdout
syms = {}
for line in r.splitlines():
    p = line.split()
    if len(p) >= 3 and p[1] in 'TtDdBb' and re.match(r'^[A-Za-z0-9_]+$', p[2]):
        try: syms[p[2]] = int(p[0], 16)
        except ValueError: pass
id = lambda s: re.sub(r'\W', '_', s)
data = open(binimg, 'rb').read()
with open(out, 'w') as f:
    f.write('// Auto-generated by tools/gen_js_blob.sh - DO NOT EDIT\n')
    f.write('// Position-independent freestanding JS engine blob (x86-64, SysV-internal).\n')
    f.write('#pragma once\n#include <cstdint>\n\n')
    f.write('// Entry-point offsets into the blob (VMA = blob offset).\n')
    for s, v in sorted(syms.items()):
        f.write('static constexpr uint32_t kJs%s = 0x%x;\n' % (id(s).capitalize(), v))
    f.write('\nstatic constexpr uint32_t kJsBlobEntry = kJsJsrt_entry;\n')
    f.write('static const uint8_t kJsBlob[] = {\n')
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        f.write('    ' + ','.join('0x%02x'%b for b in chunk) + ',\n')
    f.write('};\n')
    f.write('static constexpr uint32_t kJsBlobSize = %d;\n' % len(data))
print('Wrote %s (%d bytes, syms=%d)' % (out, len(data), len(syms)))
PY