#!/bin/bash
# Generates src/asm_blob.h from tools/asmrt.asm (freestanding, position-
# independent x86-64 two-pass assembler). The blob is embedded into the Zenith
# .text section of every PE/ELF that calls assemble() and invoked via
# `call rel32` (SysV-internal staging, like the disasm/js/tls blobs).
#
# ABI: entry asm_entry(op=rdi,a1=rsi,a2=rdx,a3=rcx,a4=r8,a5=r9); result rax.
#   op 1  a1=dst a2=cap a3=src a4=srcLen a5=origin -- assemble into dst and
#         return the exact byte count the output needs.
#   op 2  a1=errbuf a2=cap -- copy the last error message, return its length.
#   op 3  same as op 1 but nothing is written (size probe).
#
# The image is padded out to __bss_end so the arena the assembler keeps in its
# .bss travels with the code: a blob copied into .text at an unknown address
# has no other place to put it.
set -euo pipefail

cd "$(dirname "$0")/.."
OUT=src/asm_blob.h
LD=tools/asmrt.ld

OBJDIR=/tmp/asmblob
rm -rf "$OBJDIR"; mkdir -p "$OBJDIR"

# %include is resolved against the working directory, so nasm runs from tools/
( cd tools && nasm -f elf64 asmrt.asm -o "$OBJDIR/asmrt.o" )

ld -o "$OBJDIR/asmrt.img" -T "$LD" -e asm_entry "$OBJDIR/asmrt.o"

# Position-independence gate: any absolute relocation left in the image means a
# pointer that only works at link address 0 — and the blob is never there.
rel=$(readelf -r "$OBJDIR/asmrt.img" || true)
if printf '%s\n' "$rel" | grep -qE 'R_X86_64_(64|32|32S)[[:space:]]'; then
    echo "gen_asm_blob.sh: the blob is NOT position-independent:" >&2
    printf '%s\n' "$rel" | grep -E 'R_X86_64_(64|32|32S)[[:space:]]' | head -20 >&2
    echo "Every operand in tools/asmrt*.asm must use [rel ...] (default rel)." >&2
    exit 1
fi

objcopy -O binary "$OBJDIR/asmrt.img" "$OBJDIR/asmrt.bin"

python3 - "$OBJDIR/asmrt.img" "$OBJDIR/asmrt.bin" "$OUT" <<'PY'
import re, sys, subprocess

img, binimg, out = sys.argv[1], sys.argv[2], sys.argv[3]

syms = {}
for line in subprocess.run(['nm', img], capture_output=True, text=True).stdout.splitlines():
    p = line.split()
    if len(p) >= 3 and p[1] in 'TtDdBb' and re.match(r'^[A-Za-z0-9_]+$', p[2]):
        try: syms[p[2]] = int(p[0], 16)
        except ValueError: pass

data = bytearray(open(binimg, 'rb').read())
bss_end = syms.get('__bss_end')
if bss_end is None:
    sys.stderr.write('gen_asm_blob.sh: __bss_end missing from %s\n' % img)
    sys.exit(1)
if len(data) > bss_end:
    sys.stderr.write('gen_asm_blob.sh: image (%d) runs past __bss_end (%d)\n'
                      % (len(data), bss_end))
    sys.exit(1)
# .bss has no file bytes; pad so the arena ships inside the array.
data += b'\0' * (bss_end - len(data))

id_ = lambda s: re.sub(r'\W', '_', s)
with open(out, 'w') as f:
    f.write('// Auto-generated by tools/gen_asm_blob.sh - DO NOT EDIT\n')
    f.write('// Position-independent freestanding x86-64 assembler blob\n')
    f.write('// generated from tools/asmrt.asm. The array already covers the\n')
    f.write("// assembler's .bss arena, so it is written verbatim and entered\n")
    f.write('// with `call rel32`.\n')
    f.write('#pragma once\n#include <cstdint>\n\n')
    f.write('// Entry-point offsets into the blob (VMA = blob offset).\n')
    for s, v in sorted(syms.items()):
        f.write('static constexpr uint32_t kAsm%s = 0x%x;\n' % (id_(s).capitalize(), v))
    f.write('\nstatic constexpr uint32_t kAsmBlobEntry = kAsmAsm_entry;\n')
    f.write('static const uint8_t kAsmBlob[] = {\n')
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        f.write('    ' + ','.join('0x%02x' % b for b in chunk) + ',\n')
    f.write('};\n')
    f.write('static constexpr uint32_t kAsmBlobSize = %d;\n' % len(data))
print('Wrote %s (%d bytes, syms=%d, absolute relocs=0)'
      % (out, len(data), len(syms)))
PY
