#!/bin/bash
# Generates src/disasm_blob.h from tools/disasm_blob.cpp (freestanding,
# position-independent x86-64 disassembler). The blob is embedded into the
# Zenith .text section of every PE/ELF that calls disasm()/decompile() and
# invoked via `call rel32` (SysV-internal staging, like jsrt/tlsrt).
#
# ABI: entry disasm_entry(op=rdi,a1=rsi,a2=rdx,a3=rcx,a4=r8,a5=r9, s1,s2 on
# stack [rsp+8]/[rsp+16]); result in rax. The stack args ARE used by op 1
# (syntax, withAddr flags).
set -euo pipefail

cd "$(dirname "$0")/.."
OUT=src/disasm_blob.h
SRC=tools/disasm_blob.cpp
LD=tools/disasm_blob.ld

CC=gcc
OBJDIR=/tmp/disasmblob
rm -rf "$OBJDIR"; mkdir -p "$OBJDIR"

$CC -O2 -ffreestanding -fno-stack-protector -fno-ident -fno-asynchronous-unwind-tables \
    -fno-builtin -fno-common -mno-red-zone -fpic \
    -c "$SRC" -o "$OBJDIR/disasm_blob.o"

ld -o "$OBJDIR/disasm_blob.img" -T "$LD" -e disasm_entry "$OBJDIR/disasm_blob.o"

objcopy -O binary "$OBJDIR/disasm_blob.img" "$OBJDIR/disasm_blob.bin"

python3 - "$OBJDIR/disasm_blob.img" "$OBJDIR/disasm_blob.bin" "$OUT" <<'PY'
import re, sys
img, binimg, out = sys.argv[1], sys.argv[2], sys.argv[3]
import subprocess
r = subprocess.run(['nm', img], capture_output=True, text=True).stdout
syms = {}
for line in r.splitlines():
    p = line.split()
    if len(p) >= 3 and p[1] in 'TtDdBb' and re.match(r'^[A-Za-z0-9_]+$', p[2]):
        try: syms[p[2]] = int(p[0], 16)
        except ValueError: pass
id = lambda s: re.sub(r'\W', '_', s)
data = open(binimg, 'rb').read()
with open(out, 'w') as f:
    f.write('// Auto-generated by tools/gen_disasm_blob.sh - DO NOT EDIT\n')
    f.write('// \n')
    f.write('// Position-independent freestanding x86-64 disassembler blob\n')
    f.write('// (Intel + AT&T syntax) generated from tools/disasm_blob.cpp.\n')
    f.write('#pragma once\n#include <cstdint>\n\n')
    f.write('// Entry-point offsets into the blob (VMA = blob offset).\n')
    for s, v in sorted(syms.items()):
        f.write('static constexpr uint32_t kDs%s = 0x%x;\n' % (id(s).capitalize(), v))
    f.write('\nstatic constexpr uint32_t kDsBlobEntry = kDsDisasm_entry;\n')
    f.write('static const uint8_t kDsBlob[] = {\n')
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        f.write('    ' + ','.join('0x%02x'%b for b in chunk) + ',\n')
    f.write('};\n')
    f.write('static constexpr uint32_t kDsBlobSize = %d;\n' % len(data))
print('Wrote %s (%d bytes, syms=%d)' % (out, len(data), len(syms)))
PY