#!/bin/bash
# Generates src/httpdl_blob.h from tools/httpdl.c + tools/httpdl.s (the
# freestanding Linux HTTP/HTTPS download engine) LINKED TOGETHER WITH the TLS
# core (tools/tlsrt.c/.s) into one position-independent x86-64 image.
#
# The resulting blob is embedded into every Zenith Linux (`app linux`)
# binary's .text section and invoked with `call rel32` (SysV args in
# rdi/rsi/rdx/rcx/r8/r9, result in rax) — see codegen_httpdl.cpp.
#
# TLS: httpdl seeds the TLS blob's io slots (tlsrt_io_send/recv/close) with
# its own raw-syscall wrappers, then drives the handshake/records through
# tlsrt_entry — no libc, no WinSock, raw syscalls for everything.
set -euo pipefail

cd "$(dirname "$0")/.."
OUT=src/httpdl_blob.h
LD=tools/httpdl.ld

CC=gcc
OBJDIR=/tmp/httpdlblob
rm -rf "$OBJDIR"; mkdir -p "$OBJDIR"

CFLAGS="-O2 -ffreestanding -fno-stack-protector -fno-ident -fno-asynchronous-unwind-tables -fno-builtin -fpic -fno-common -mno-red-zone -fvisibility=hidden"

$CC $CFLAGS -I"$(dirname tools/tlsrt.h)" -c tools/httpdl.c -o "$OBJDIR/httpdl.o"
$CC $CFLAGS -c tools/httpdl.s -o "$OBJDIR/httpdl_asm.o"
$CC $CFLAGS -I"$(dirname tools/tlsrt.h)" -c tools/tlsrt.c -o "$OBJDIR/tlsrt.o"
$CC $CFLAGS -c tools/tlsrt.s -o "$OBJDIR/tlsrt_asm.o"

ld -o "$OBJDIR/httpdl.img" -T "$LD" -e httpdl_entry \
    "$OBJDIR/httpdl.o" "$OBJDIR/httpdl_asm.o" \
    "$OBJDIR/tlsrt.o" "$OBJDIR/tlsrt_asm.o"

objcopy -O binary "$OBJDIR/httpdl.img" "$OBJDIR/httpdl.bin"

nm "$OBJDIR/httpdl.img" | awk -v bss_file="$OBJDIR/bss_end" '
    /^[[:xdigit:]]+[[:space:]]+[TtDdBb][[:space:]]+/ {
        address = $1
        type = $2
        name = $3
        if (name == "__bss_end") {
            print address > bss_file
        }
        if (name !~ /\./ && name !~ /^__/) {
            print name, address
        }
    }
' > "$OBJDIR/symbols"
if [ ! -s "$OBJDIR/bss_end" ]; then
    printf 'missing __bss_end in %s\n' "$OBJDIR/httpdl.img" >&2
    exit 1
fi
bss_end=$((16#$(<"$OBJDIR/bss_end")))
data_size=$(stat -c%s "$OBJDIR/httpdl.bin")
if [ "$bss_end" -gt "$data_size" ]; then
    truncate -s "$bss_end" "$OBJDIR/httpdl.bin"
fi
{
    printf '%s\n' '// Auto-generated by tools/gen_httpdl_blob.sh - DO NOT EDIT'
    printf '%s\n' '// Freestanding Linux HTTP/HTTPS download engine + TLS 1.2 core'
    printf '%s\n' '// (x86-64, SysV-internal; raw syscalls, no libc).'
    printf '%s\n\n' '#pragma once'
    printf '%s\n' '#include <cstdint>'
    printf '%s\n\n' '// Entry-point offsets into the blob (VMA = blob offset).'
    LC_ALL=C sort -k1,1 "$OBJDIR/symbols" | while read -r name address; do
        printf 'static constexpr uint32_t kHttpdl%s = 0x%s;\n' "$name" "$address"
    done
    printf '\n%s\n' '// Exported blob entry point used by codegen_httpdl.cpp:'
    entry=$(awk '$1 == "httpdl_entry" { print $2; exit }' "$OBJDIR/symbols")
    if [ -n "$entry" ]; then
        printf '#define HTTPDL_BLOB_ENTRY 0x%s\n' "$entry"
    fi
    printf '\n%s\n' 'static const uint8_t kHttpdlBlob[] = {'
    od -An -v -t x1 -w16 "$OBJDIR/httpdl.bin" | awk '
        {
            line = "   "
            for (i = 1; i <= NF; i++) {
                if (i > 1) line = line ","
                line = line "0x" $i
            }
            print line ","
        }
    '
    printf '%s\n' '};'
    printf 'static constexpr uint32_t kHttpdlBlobSize = %s;\n' "$bss_end"
} > "$OUT"
printf 'Wrote %s (%d bytes, syms=%d, bss_end=0x%x)\n' "$OUT" "$bss_end" "$(wc -l < "$OBJDIR/symbols")" "$bss_end"
